# 
#
# This file contains code generated by A. Lambarri Martinez for the
# Galaxy Formation and Evolution course in the 
# Astrophysics Masters at UCM
#
# Version: Dic 11, 2023 @18:00
#
# SPDX-License-Identifier: GPL-3.0+
#

import numpy as np
import pandas as pd

def BundleMaker(box,dataFrame):
    """Returns a pandas dataframe containing V-I, I and Mbol for the selected bundle.
       Bundles can only be squares or rectangles.

       Parameters
       ----------
       box : array
           Array of shape (2,>2) compatible with numpy functions. 
           Must contains the limits of the bundle box.
       dataFrame : dataFrame
           DataFrame from which to extract the data on the desired region.
           
       Returns
       -------
       df : pandas dataFrame
           DataFrame containing V-I, I and Mbol for the objects inside the desired region.
           
    """
    mask = (dataFrame['V-I']<box[0,:].max()) & (dataFrame['V-I']>box[0,:].min()) & (dataFrame['I']<box[1,:].max()) & (dataFrame['I']>box[1,:].min())
    df = pd.DataFrame({key:dataFrame[key][mask] for key in dataFrame.columns.values})
    return df